runtime: nodejs16

env_variables:
  PORT: 8080
  DEBUG: "True"
  DATABASE_FILE: "suraksha.db"
  ACC_THRESHOLD: "15.0"
  GYRO_THRESHOLD: "45.0"
  IMPACT_DURATION_MS: "200"
  CONSECUTIVE_DETECTIONS_REQUIRED: "3"
  VIDEO_CALL_TIMEOUT_SECONDS: "60"
